# Generated by Django 4.1.3 on 2022-12-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="dish", options={"ordering": ("name",)},),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
