# Generated by Django 4.1.3 on 2022-12-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dish", "0002_alter_dish_options_alter_dish_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
